CREATE TABLE IF NOT EXISTS `i7b0_mpDetails` (
  `mpId` int(11) NOT NULL,
  `firstName` varchar(100) DEFAULT NULL,
  `lastName` varchar(100) DEFAULT NULL,
  `mpName` varchar(200) DEFAULT NULL,
  `party` varchar(50) DEFAULT NULL,
  `twitter` varchar(50) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `constituency` varchar(100) DEFAULT NULL,
  `constituencyAddress` varchar(200) DEFAULT NULL,
  `edmStatus` varchar(30) DEFAULT NULL,
  `ministerialStatus` varchar(200) DEFAULT NULL,
  `url` varchar(200) DEFAULT NULL,
  `edmUrl` varchar(200) DEFAULT NULL,
  `majority` int(11) DEFAULT NULL,
  `pCon` varchar(20) DEFAULT NULL,
  `mpGroupNo` int(11) DEFAULT NULL,
  `telNo` varchar(30) DEFAULT NULL,
  `campaignNotes` mediumtext,
  `sharedCampaignEmails` text,
  `privateCampaignEmails` text,
  `uidAdministrator` int(11) DEFAULT NULL,
  `IsSystem` tinyint(4) DEFAULT NULL,
  `tags` varchar(200) DEFAULT NULL,
  `parliamentaryEmail` varchar(100) DEFAULT NULL,
  `constituencyEmail` varchar(100) DEFAULT NULL,
  `properName` varchar(100) DEFAULT NULL,
  `consTelNo` varchar(20) DEFAULT NULL,
  `parlTelNo` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`mpId`),
  KEY `mpDetails_mpName` (`mpName`),
  KEY `mpDetails_constituency` (`constituency`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;